### PR TITLE
Re-enable the GridView

### PR DESCRIPTION
**Pull request by nickfong**
Fix a handful of bugs that were introduced when changing the way the GridView interacted with QSettings.  The GridView shows up when selected in preferences, and the last opened view now opens when the user runs cadnano.

### CODE REVIEW

**Comment by nickfong** [comment]
That's definitely not the expected behavior.  

This is what the GridView looks like locally for me:
screenshot 2018-02-28 09 32 43

And the SliceView:
screenshot 2018-02-28 09 33 18

**Comment by sdouglas** [comment]
Ok, I only checked out your branch `nickfong:nbf/gridview-enable` to test. I see this behavior immediately without restarting the app. Perhaps one of us has some residual window layout/geometry settings. We can temporarily change the application string that is passed to QSettings to see what it looks like to a new user.

**Comment by nickfong** [comment]
Thanks for the suggestion @sdouglas!

In `preferences.py` I changed 
```
self.qs = QSettings("cadnano.org", "cadnano2.5")
```
to
```
self.qs = QSettings("69bfae41ee5e33c689fded70c89cc64c", "69bfae41ee5e33c689fded70c89cc64c")
```
and restarted `cadnano`.  It looks like the layout is OK:

screenshot 2018-02-28 10 13 11
screenshot 2018-02-28 10 13 16

Should I commit this change (and revert before merging) so you can review properly?

**Comment by nickfong** [comment]
I stand corrected... I replaced 2 of the 3 instances of `QSettings`; looks like I'm able to reproduce this now after replacing the 3rd instance.  I'll look into why this is happening.  Thanks for the feedback @sdouglas!

**Comment by sdouglas** [comment]
The previous bug seems fixed. However, the gridview dockwidget layout & geometry doesn't seem to save or restore itself correctly like the other dockwidgets. Instead, it resets to a wide default width when enabledin the prefs dialog, as well as closing and re-opening the app.

**Comment by grinner** [comment]
This seems like it's good enough for `develop`.  I got a crash when toggling the Grid Appearance.  I think we can fix that pretty fast.

**Pull request merged**
